edition = "2024"
style_edition = "2024"

max_width = 120
array_width = 80
chain_width = 80

hard_tabs = false
tab_spaces = 4

reorder_imports = false
reorder_modules = false

format_code_in_doc_comments = true
wrap_comments = false

trailing_comma = "Never"
hex_literal_case = "Upper"