name: Build & Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.repository_id }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    strategy:
      matrix:
        target:
          - target: "x86_64-unknown-linux-gnu"

          - target: "x86_64-unknown-linux-musl"

          - target: "aarch64-unknown-linux-gnu"

          - target: "aarch64-unknown-linux-musl"

          - os: windows-2025
            toolchain: "x86_64-pc-windows-msvc"
            target: "x86_64-pc-windows-msvc"

          - os: windows-11-arm
            toolchain: "aarch64-pc-windows-msvc"
            target: "aarch64-pc-windows-msvc"

          - os: macos-15
            toolchain: "aarch64-apple-darwin"
            target: "aarch64-apple-darwin"

        toolchain_version:
          - "stable"
          - "nightly"

      fail-fast: false

    name: Build & Test ${{ matrix.target.target }} (${{ matrix.toolchain_version || 'stable' }})
    runs-on: ${{ matrix.target.os || 'ubuntu-24.04' }}
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Why does Windows aarch64 not come with rustup
        if: ${{ matrix.target.os == 'windows-11-arm' }}
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://static.rust-lang.org/rustup/dist/${{ matrix.target.toolchain || 'x86_64-unknown-linux-gnu' }}/rustup-init.exe" -Outfile "C:\temp\rustup-init.exe"
          & "C:\temp\rustup-init.exe" -y
          Write-Output "$env:USERPROFILE\.cargo\bin" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH

      - name: Install Rust
        run: |
          rustup toolchain install ${{ matrix.toolchain_version || 'stable' }}-${{ matrix.target.toolchain || 'x86_64-unknown-linux-gnu' }} --profile default --component rustc,cargo,rust-std,rust-src --allow-downgrade
          rustup default ${{ matrix.toolchain_version || 'stable' }}-${{ matrix.target.toolchain || 'x86_64-unknown-linux-gnu' }}

      - name: Install cross-toolchain
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target.target }}

      - name: Build
        if: ${{ matrix.toolchain_version != 'nightly' }}
        run: |
          cargo build --release --all-targets --target ${{ matrix.target.target }}

      - name: Build Nightly
        if: ${{ matrix.toolchain_version == 'nightly' }}
        run: |
          cargo build --release --all-targets --target ${{ matrix.target.target }} -Z build-std

      - name: Test
        if: ${{ !matrix.target.no_test && matrix.toolchain_version != 'nightly' }}
        run: |
          cargo test --locked --release --all-targets --target ${{ matrix.target.target }} --no-fail-fast

      - name: Test Nightly
        if: ${{ !matrix.target.no_test && matrix.toolchain_version == 'nightly' }}
        run: |
          cargo test --locked --release --all-targets --target ${{ matrix.target.target }} -Z build-std --no-fail-fast
